name: cots_2211104071
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/design_system/image/gojek_logo.png
    - lib/design_system/image/onboarding1.png
    - lib/design_system/image/onboarding2.png
    - lib/design_system/image/onboarding3.png
    